import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/index.tsx"),
  route("app", "routes/app-layout.tsx", [
    index("routes/dashboard.tsx"),
    route("studio/chat", "routes/workbench.tsx"),
    route("studio/images", "routes/studio-images.tsx"),
    route("studio/audio", "routes/studio-audio.tsx"),
    route("studio/rerank", "routes/studio-rerank.tsx"),
    route("studio/advanced", "routes/studio-advanced.tsx"),
    route("local/choose", "routes/local-choose.tsx"),
    route("local/models", "routes/local-models.tsx"),
    route("local/peer-models", "routes/local-peer-models.tsx"),
    route("local/llama-swap/models", "routes/local-llama-swap-models.tsx"),
    route("local/llama-swap/swap", "routes/local-swap.tsx"),
    route("local/llama-swap/policy", "routes/local-policy.tsx"),
    route("local/llama-swap/logs", "routes/local-logs.tsx"),
    route("local/llama-swap/matrix", "routes/local-matrix.tsx"),
    route("local/swap", "routes/legacy-redirect.tsx", { id: "legacy-local-swap" }),
    route("local/policy", "routes/legacy-redirect.tsx", { id: "legacy-local-policy" }),
    route("local/logs", "routes/legacy-redirect.tsx", { id: "legacy-local-logs" }),
    route("local/matrix", "routes/legacy-redirect.tsx", { id: "legacy-local-matrix" }),
    route("local/endpoints", "routes/local-peers.tsx"),
    route("local/peers", "routes/legacy-redirect.tsx", { id: "legacy-local-peers" }),
    route("remote/providers", "routes/providers.tsx"),
    route("control/providers", "routes/legacy-redirect.tsx", { id: "legacy-control-providers" }),
    route("router/strategy", "routes/control-routing-strategy.tsx"),
    route("control/routing-strategy", "routes/legacy-redirect.tsx", {
      id: "legacy-control-routing-strategy",
    }),
    route("system/runtime-config", "routes/control-runtime-config.tsx"),
    route("control/runtime-config", "routes/legacy-redirect.tsx", {
      id: "legacy-control-runtime-config",
    }),
    route("router/controller", "routes/control-controller.tsx"),
    route("control/controller", "routes/legacy-redirect.tsx", { id: "legacy-control-controller" }),
    route("connect", "routes/endpoints.tsx"),
    route("connect/downstream", "routes/integrations-downstream.tsx"),
    route("connect/upstream", "routes/integrations-upstream.tsx"),
    route("endpoints", "routes/legacy-redirect.tsx", { id: "legacy-endpoints" }),
    route("control/endpoints", "routes/legacy-redirect.tsx", { id: "legacy-control-endpoints" }),
    route("models/roles", "routes/control-roles.tsx"),
    route("control/roles", "routes/legacy-redirect.tsx", { id: "legacy-control-roles" }),
    route("models", "routes/control-models.tsx"),
    route("models/benchmark", "routes/control-benchmark.tsx"),
    route("control/benchmark", "routes/legacy-redirect.tsx", { id: "legacy-control-benchmark" }),
    route("control/models", "routes/legacy-redirect.tsx", { id: "legacy-control-models" }),
    route("router", "routes/router.tsx"),
    route("router/config", "routes/router-config.tsx"),
    route("router/candidates", "routes/router-candidates.tsx"),
    route("router/decisions", "routes/router-decisions.tsx"),
    route("router/decisions/:requestId", "routes/router-decision-detail.tsx"),
    route("observe", "routes/legacy-redirect.tsx", { id: "legacy-observe" }),
    route("observe/activity", "routes/observe-activity.tsx"),
    route("observe/requests", "routes/requests.tsx"),
    route("observe/requests/:requestId", "routes/request-detail.tsx"),
    route("observe/logs", "routes/observe-logs.tsx"),
    route("endpoints/downstream", "routes/legacy-redirect.tsx", {
      id: "legacy-endpoints-downstream",
    }),
    route("integrations/downstream", "routes/legacy-redirect.tsx", {
      id: "legacy-integrations-downstream",
    }),
    route("endpoints/upstream", "routes/legacy-redirect.tsx", {
      id: "legacy-endpoints-upstream",
    }),
    route("integrations/upstream", "routes/legacy-redirect.tsx", {
      id: "legacy-integrations-upstream",
    }),
    route("system/runtime", "routes/runtime.tsx"),
    route("system/session-readiness", "routes/session-readiness.tsx"),
    route("control/session-readiness", "routes/legacy-redirect.tsx", {
      id: "legacy-control-session-readiness",
    }),
    route("system/peers", "routes/system-peers.tsx"),
  ]),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
