import path from "node:path";
// Production launcher: uses QA's working approach with production state
import { createRuntimeBridgeBackend, startBridgeServer } from "../src/index.js";

const repoRoot = "D:/DEV/role-model";
const runtimeStateRoot = "C:/Users/erikb/AppData/Local/Role Model Runtime/state";
const scopeId = "runtime-host-bridge";

const backend = await createRuntimeBridgeBackend({
  repoRoot,
  runtimeStateRoot,
  scopeId,
  runtimeVendorStartup: "enabled",
  unifiedRuntimeConfigPath: `${runtimeStateRoot}/${scopeId}/runtime-config.yaml`,
});

const server = await startBridgeServer({
  host: "127.0.0.1",
  port: 3456,
  staticRoot: path.join(repoRoot, "role-model-router", "apps", "runtime-ui", "build", "client"),
  registry: backend.registry,
  getRegistry: () => backend.registry,
  executeChatCompletions: backend.executeChatCompletions,
  executeResponses: backend.executeResponses,
  readHealthStatus: backend.readHealthStatus,
  getRoutableInventory: backend.getRoutableInventory,
  readVersionInfo: backend.readVersionInfo,
  readLogs: async () => (await backend.getLocalLogs()).logs,
  listActivityMetrics: backend.listActivityMetrics,
  readActivityCapture: backend.readActivityCapture,
  readRuntimeSummary: backend.readRuntimeSummary,
  readRuntimeConfig: backend.readRuntimeConfig,
  updateRuntimeConfig: backend.updateRuntimeConfig,
  readTelemetrySummary: backend.readTelemetrySummary,
  listTelemetryComparisonRows: backend.listTelemetryComparisonRows,
  listTelemetryRequests: backend.listTelemetryRequests,
  queryTelemetryAnalytics: backend.queryTelemetryAnalytics,
  subscribeTelemetry: backend.subscribeTelemetry,
  listProviders: backend.listProviders,
  listRoles: backend.listRoles,
  listModels: backend.listModels,
  listExtensions: backend.listExtensions,
  readStorageRetention: backend.readStorageRetention,
  dryRunStorageRetention: backend.dryRunStorageRetention,
  readRolePolicy: backend.readRolePolicy,
  createRolePolicyRole: backend.createRolePolicyRole,
  updateRolePolicyRole: backend.updateRolePolicyRole,
  listTaskDefinitions: backend.listTaskDefinitions,
  updateTaskDefinitions: backend.updateTaskDefinitions,
  listAccounts: backend.listAccounts,
  listProviderDeviceAuthorizations: backend.listProviderDeviceAuthorizations,
  upsertProviderAccount: backend.upsertProviderAccount,
  startProviderDeviceAuthorization: backend.startProviderDeviceAuthorization,
  pollProviderDeviceAuthorization: backend.pollProviderDeviceAuthorization,
  removeProviderAccountModel: backend.removeProviderAccountModel,
  activateEndpoint: backend.activateEndpoint,
  readControllerAssignment: backend.readControllerAssignment,
  updateControllerAssignment: backend.updateControllerAssignment,
  readRouterSummary: backend.readRouterSummary,
  readRouterConfig: backend.readRouterConfig,
  listRouterCandidates: backend.listRouterCandidates,
  listRouterDecisions: backend.listRouterDecisions,
  readRouterDecision: backend.readRouterDecision,
  listEndpoints: backend.listEndpoints,
  listRecentRequestIds: backend.listRecentRequestIds,
  listRecentRequestObservations: backend.listRecentRequestObservations,
  readRequestObservation: backend.readRequestObservation,
  readEndpointProfile: backend.readEndpointProfile,
  readBenchmarkSuite: backend.readBenchmarkSuite,
  runBenchmark: backend.runBenchmark,
  readBenchmarkRun: backend.readBenchmarkRun,
  readActiveBenchmarkRun: backend.readActiveBenchmarkRun,
  clearBenchmarkEndpointData: backend.clearBenchmarkEndpointData,
  clearBenchmarkData: backend.clearBenchmarkData,
  readBenchmarkSummary: backend.readBenchmarkSummary,
  listBenchmarkRuns: backend.listBenchmarkRuns,
  readBenchmarkSummariesByMode: backend.readBenchmarkSummariesByMode,
  readBenchmarkPreferences: backend.readBenchmarkPreferences,
  updateBenchmarkPreferences: backend.updateBenchmarkPreferences,
  listLocalModels: backend.listLocalModels,
  listPeerLocalModels: backend.listPeerLocalModels,
  listLlamaSwapLocalModels: backend.listLlamaSwapLocalModels,
  loadLocalModel: backend.loadLocalModel,
  loadPeerModel: backend.loadPeerModel,
  loadLlamaSwapModel: backend.loadLlamaSwapModel,
  setPeerModelRoles: backend.setPeerModelRoles,
  setLlamaSwapModelRoles: backend.setLlamaSwapModelRoles,
  unloadPeerModel: backend.unloadPeerModel,
  unloadLocalModel: backend.unloadLocalModel,
  readLocalPolicy: backend.readLocalPolicy,
  updateLocalPolicy: backend.updateLocalPolicy,
  listSwapHistory: backend.listSwapHistory,
  getLocalLogs: backend.getLocalLogs,
  readModelOverrides: backend.readModelOverrides,
  updateModelOverrides: backend.updateModelOverrides,
  readPeers: backend.readPeers,
  updatePeers: backend.updatePeers,
  checkPeerHealth: backend.checkPeerHealth,
});

console.log(`Production runtime on http://127.0.0.1:${server.port}`);
process.on("SIGINT", () => {
  server.close();
  process.exit(0);
});
