// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/providers": {
    params: {};
  };
  "/app/accounts": {
    params: {};
  };
  "/app/workbench": {
    params: {};
  };
  "/app/runtime": {
    params: {};
  };
  "/app/endpoints": {
    params: {};
  };
  "/app/requests": {
    params: {};
  };
  "/app/requests/:requestId": {
    params: {
      "requestId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/app" | "/app/providers" | "/app/accounts" | "/app/workbench" | "/app/runtime" | "/app/endpoints" | "/app/requests" | "/app/requests/:requestId" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/app-layout.tsx": {
    id: "routes/app-layout";
    page: "/app" | "/app/providers" | "/app/accounts" | "/app/workbench" | "/app/runtime" | "/app/endpoints" | "/app/requests" | "/app/requests/:requestId";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/app";
  };
  "routes/providers.tsx": {
    id: "routes/providers";
    page: "/app/providers";
  };
  "routes/accounts.tsx": {
    id: "routes/accounts";
    page: "/app/accounts";
  };
  "routes/workbench.tsx": {
    id: "routes/workbench";
    page: "/app/workbench";
  };
  "routes/runtime.tsx": {
    id: "routes/runtime";
    page: "/app/runtime";
  };
  "routes/endpoints.tsx": {
    id: "routes/endpoints";
    page: "/app/endpoints";
  };
  "routes/requests.tsx": {
    id: "routes/requests";
    page: "/app/requests";
  };
  "routes/request-detail.tsx": {
    id: "routes/request-detail";
    page: "/app/requests/:requestId";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/app-layout": typeof import("./app/routes/app-layout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/providers": typeof import("./app/routes/providers.tsx");
  "routes/accounts": typeof import("./app/routes/accounts.tsx");
  "routes/workbench": typeof import("./app/routes/workbench.tsx");
  "routes/runtime": typeof import("./app/routes/runtime.tsx");
  "routes/endpoints": typeof import("./app/routes/endpoints.tsx");
  "routes/requests": typeof import("./app/routes/requests.tsx");
  "routes/request-detail": typeof import("./app/routes/request-detail.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};