// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/studio/chat": {
    params: {};
  };
  "/app/studio/images": {
    params: {};
  };
  "/app/studio/audio": {
    params: {};
  };
  "/app/studio/rerank": {
    params: {};
  };
  "/app/studio/advanced": {
    params: {};
  };
  "/app/local/models": {
    params: {};
  };
  "/app/local/swap": {
    params: {};
  };
  "/app/local/policy": {
    params: {};
  };
  "/app/local/logs": {
    params: {};
  };
  "/app/local/matrix": {
    params: {};
  };
  "/app/local/endpoints": {
    params: {};
  };
  "/app/local/peers": {
    params: {};
  };
  "/app/remote/providers": {
    params: {};
  };
  "/app/control/providers": {
    params: {};
  };
  "/app/router/strategy": {
    params: {};
  };
  "/app/control/routing-strategy": {
    params: {};
  };
  "/app/system/runtime-config": {
    params: {};
  };
  "/app/control/runtime-config": {
    params: {};
  };
  "/app/router/controller": {
    params: {};
  };
  "/app/control/controller": {
    params: {};
  };
  "/app/endpoints": {
    params: {};
  };
  "/app/control/endpoints": {
    params: {};
  };
  "/app/models/roles": {
    params: {};
  };
  "/app/control/roles": {
    params: {};
  };
  "/app/models": {
    params: {};
  };
  "/app/control/models": {
    params: {};
  };
  "/app/router": {
    params: {};
  };
  "/app/router/config": {
    params: {};
  };
  "/app/router/candidates": {
    params: {};
  };
  "/app/router/decisions": {
    params: {};
  };
  "/app/router/decisions/:requestId": {
    params: {
      "requestId": string;
    };
  };
  "/app/observe/activity": {
    params: {};
  };
  "/app/observe/requests": {
    params: {};
  };
  "/app/observe/requests/:requestId": {
    params: {
      "requestId": string;
    };
  };
  "/app/observe/logs": {
    params: {};
  };
  "/app/endpoints/downstream": {
    params: {};
  };
  "/app/integrations/downstream": {
    params: {};
  };
  "/app/endpoints/upstream": {
    params: {};
  };
  "/app/integrations/upstream": {
    params: {};
  };
  "/app/system/runtime": {
    params: {};
  };
  "/app/system/peers": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/app" | "/app/studio/chat" | "/app/studio/images" | "/app/studio/audio" | "/app/studio/rerank" | "/app/studio/advanced" | "/app/local/models" | "/app/local/swap" | "/app/local/policy" | "/app/local/logs" | "/app/local/matrix" | "/app/local/endpoints" | "/app/local/peers" | "/app/remote/providers" | "/app/control/providers" | "/app/router/strategy" | "/app/control/routing-strategy" | "/app/system/runtime-config" | "/app/control/runtime-config" | "/app/router/controller" | "/app/control/controller" | "/app/endpoints" | "/app/control/endpoints" | "/app/models/roles" | "/app/control/roles" | "/app/models" | "/app/control/models" | "/app/router" | "/app/router/config" | "/app/router/candidates" | "/app/router/decisions" | "/app/router/decisions/:requestId" | "/app/observe/activity" | "/app/observe/requests" | "/app/observe/requests/:requestId" | "/app/observe/logs" | "/app/endpoints/downstream" | "/app/integrations/downstream" | "/app/endpoints/upstream" | "/app/integrations/upstream" | "/app/system/runtime" | "/app/system/peers" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/app-layout.tsx": {
    id: "routes/app-layout";
    page: "/app" | "/app/studio/chat" | "/app/studio/images" | "/app/studio/audio" | "/app/studio/rerank" | "/app/studio/advanced" | "/app/local/models" | "/app/local/swap" | "/app/local/policy" | "/app/local/logs" | "/app/local/matrix" | "/app/local/endpoints" | "/app/local/peers" | "/app/remote/providers" | "/app/control/providers" | "/app/router/strategy" | "/app/control/routing-strategy" | "/app/system/runtime-config" | "/app/control/runtime-config" | "/app/router/controller" | "/app/control/controller" | "/app/endpoints" | "/app/control/endpoints" | "/app/models/roles" | "/app/control/roles" | "/app/models" | "/app/control/models" | "/app/router" | "/app/router/config" | "/app/router/candidates" | "/app/router/decisions" | "/app/router/decisions/:requestId" | "/app/observe/activity" | "/app/observe/requests" | "/app/observe/requests/:requestId" | "/app/observe/logs" | "/app/endpoints/downstream" | "/app/integrations/downstream" | "/app/endpoints/upstream" | "/app/integrations/upstream" | "/app/system/runtime" | "/app/system/peers";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/app";
  };
  "routes/workbench.tsx": {
    id: "routes/workbench";
    page: "/app/studio/chat";
  };
  "routes/studio-images.tsx": {
    id: "routes/studio-images";
    page: "/app/studio/images";
  };
  "routes/studio-audio.tsx": {
    id: "routes/studio-audio";
    page: "/app/studio/audio";
  };
  "routes/studio-rerank.tsx": {
    id: "routes/studio-rerank";
    page: "/app/studio/rerank";
  };
  "routes/studio-advanced.tsx": {
    id: "routes/studio-advanced";
    page: "/app/studio/advanced";
  };
  "routes/local-models.tsx": {
    id: "routes/local-models";
    page: "/app/local/models";
  };
  "routes/local-swap.tsx": {
    id: "routes/local-swap";
    page: "/app/local/swap";
  };
  "routes/local-policy.tsx": {
    id: "routes/local-policy";
    page: "/app/local/policy";
  };
  "routes/local-logs.tsx": {
    id: "routes/local-logs";
    page: "/app/local/logs";
  };
  "routes/local-matrix.tsx": {
    id: "routes/local-matrix";
    page: "/app/local/matrix";
  };
  "routes/local-peers.tsx": {
    id: "routes/local-peers";
    page: "/app/local/endpoints";
  };
  "routes/legacy-redirect.tsx": {
    id: "legacy-local-peers";
    page: "/app/local/peers";
  } | {
    id: "legacy-control-providers";
    page: "/app/control/providers";
  } | {
    id: "legacy-control-routing-strategy";
    page: "/app/control/routing-strategy";
  } | {
    id: "legacy-control-runtime-config";
    page: "/app/control/runtime-config";
  } | {
    id: "legacy-control-controller";
    page: "/app/control/controller";
  } | {
    id: "legacy-control-endpoints";
    page: "/app/control/endpoints";
  } | {
    id: "legacy-control-roles";
    page: "/app/control/roles";
  } | {
    id: "legacy-control-models";
    page: "/app/control/models";
  } | {
    id: "legacy-integrations-downstream";
    page: "/app/integrations/downstream";
  } | {
    id: "legacy-integrations-upstream";
    page: "/app/integrations/upstream";
  };
  "routes/providers.tsx": {
    id: "routes/providers";
    page: "/app/remote/providers";
  };
  "routes/control-routing-strategy.tsx": {
    id: "routes/control-routing-strategy";
    page: "/app/router/strategy";
  };
  "routes/control-runtime-config.tsx": {
    id: "routes/control-runtime-config";
    page: "/app/system/runtime-config";
  };
  "routes/control-controller.tsx": {
    id: "routes/control-controller";
    page: "/app/router/controller";
  };
  "routes/endpoints.tsx": {
    id: "routes/endpoints";
    page: "/app/endpoints";
  };
  "routes/control-roles.tsx": {
    id: "routes/control-roles";
    page: "/app/models/roles";
  };
  "routes/control-models.tsx": {
    id: "routes/control-models";
    page: "/app/models";
  };
  "routes/router.tsx": {
    id: "routes/router";
    page: "/app/router";
  };
  "routes/router-config.tsx": {
    id: "routes/router-config";
    page: "/app/router/config";
  };
  "routes/router-candidates.tsx": {
    id: "routes/router-candidates";
    page: "/app/router/candidates";
  };
  "routes/router-decisions.tsx": {
    id: "routes/router-decisions";
    page: "/app/router/decisions";
  };
  "routes/router-decision-detail.tsx": {
    id: "routes/router-decision-detail";
    page: "/app/router/decisions/:requestId";
  };
  "routes/observe-activity.tsx": {
    id: "routes/observe-activity";
    page: "/app/observe/activity";
  };
  "routes/requests.tsx": {
    id: "routes/requests";
    page: "/app/observe/requests";
  };
  "routes/request-detail.tsx": {
    id: "routes/request-detail";
    page: "/app/observe/requests/:requestId";
  };
  "routes/observe-logs.tsx": {
    id: "routes/observe-logs";
    page: "/app/observe/logs";
  };
  "routes/integrations-downstream.tsx": {
    id: "routes/integrations-downstream";
    page: "/app/endpoints/downstream";
  };
  "routes/integrations-upstream.tsx": {
    id: "routes/integrations-upstream";
    page: "/app/endpoints/upstream";
  };
  "routes/runtime.tsx": {
    id: "routes/runtime";
    page: "/app/system/runtime";
  };
  "routes/system-peers.tsx": {
    id: "routes/system-peers";
    page: "/app/system/peers";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/app-layout": typeof import("./app/routes/app-layout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/workbench": typeof import("./app/routes/workbench.tsx");
  "routes/studio-images": typeof import("./app/routes/studio-images.tsx");
  "routes/studio-audio": typeof import("./app/routes/studio-audio.tsx");
  "routes/studio-rerank": typeof import("./app/routes/studio-rerank.tsx");
  "routes/studio-advanced": typeof import("./app/routes/studio-advanced.tsx");
  "routes/local-models": typeof import("./app/routes/local-models.tsx");
  "routes/local-swap": typeof import("./app/routes/local-swap.tsx");
  "routes/local-policy": typeof import("./app/routes/local-policy.tsx");
  "routes/local-logs": typeof import("./app/routes/local-logs.tsx");
  "routes/local-matrix": typeof import("./app/routes/local-matrix.tsx");
  "routes/local-peers": typeof import("./app/routes/local-peers.tsx");
  "legacy-local-peers": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/providers": typeof import("./app/routes/providers.tsx");
  "legacy-control-providers": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/control-routing-strategy": typeof import("./app/routes/control-routing-strategy.tsx");
  "legacy-control-routing-strategy": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/control-runtime-config": typeof import("./app/routes/control-runtime-config.tsx");
  "legacy-control-runtime-config": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/control-controller": typeof import("./app/routes/control-controller.tsx");
  "legacy-control-controller": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/endpoints": typeof import("./app/routes/endpoints.tsx");
  "legacy-control-endpoints": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/control-roles": typeof import("./app/routes/control-roles.tsx");
  "legacy-control-roles": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/control-models": typeof import("./app/routes/control-models.tsx");
  "legacy-control-models": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/router": typeof import("./app/routes/router.tsx");
  "routes/router-config": typeof import("./app/routes/router-config.tsx");
  "routes/router-candidates": typeof import("./app/routes/router-candidates.tsx");
  "routes/router-decisions": typeof import("./app/routes/router-decisions.tsx");
  "routes/router-decision-detail": typeof import("./app/routes/router-decision-detail.tsx");
  "routes/observe-activity": typeof import("./app/routes/observe-activity.tsx");
  "routes/requests": typeof import("./app/routes/requests.tsx");
  "routes/request-detail": typeof import("./app/routes/request-detail.tsx");
  "routes/observe-logs": typeof import("./app/routes/observe-logs.tsx");
  "routes/integrations-downstream": typeof import("./app/routes/integrations-downstream.tsx");
  "legacy-integrations-downstream": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/integrations-upstream": typeof import("./app/routes/integrations-upstream.tsx");
  "legacy-integrations-upstream": typeof import("./app/routes/legacy-redirect.tsx");
  "routes/runtime": typeof import("./app/routes/runtime.tsx");
  "routes/system-peers": typeof import("./app/routes/system-peers.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};