// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/studio/chat": {
    params: {};
  };
  "/app/studio/images": {
    params: {};
  };
  "/app/studio/audio": {
    params: {};
  };
  "/app/studio/rerank": {
    params: {};
  };
  "/app/studio/advanced": {
    params: {};
  };
  "/app/control/providers": {
    params: {};
  };
  "/app/control/accounts": {
    params: {};
  };
  "/app/control/runtime-config": {
    params: {};
  };
  "/app/control/controller": {
    params: {};
  };
  "/app/control/endpoints": {
    params: {};
  };
  "/app/control/models": {
    params: {};
  };
  "/app/observe/activity": {
    params: {};
  };
  "/app/observe/requests": {
    params: {};
  };
  "/app/observe/requests/:requestId": {
    params: {
      "requestId": string;
    };
  };
  "/app/observe/logs": {
    params: {};
  };
  "/app/integrations/downstream": {
    params: {};
  };
  "/app/integrations/upstream": {
    params: {};
  };
  "/app/system/runtime": {
    params: {};
  };
  "/app/system/peers": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/app" | "/app/studio/chat" | "/app/studio/images" | "/app/studio/audio" | "/app/studio/rerank" | "/app/studio/advanced" | "/app/control/providers" | "/app/control/accounts" | "/app/control/runtime-config" | "/app/control/controller" | "/app/control/endpoints" | "/app/control/models" | "/app/observe/activity" | "/app/observe/requests" | "/app/observe/requests/:requestId" | "/app/observe/logs" | "/app/integrations/downstream" | "/app/integrations/upstream" | "/app/system/runtime" | "/app/system/peers" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/app-layout.tsx": {
    id: "routes/app-layout";
    page: "/app" | "/app/studio/chat" | "/app/studio/images" | "/app/studio/audio" | "/app/studio/rerank" | "/app/studio/advanced" | "/app/control/providers" | "/app/control/accounts" | "/app/control/runtime-config" | "/app/control/controller" | "/app/control/endpoints" | "/app/control/models" | "/app/observe/activity" | "/app/observe/requests" | "/app/observe/requests/:requestId" | "/app/observe/logs" | "/app/integrations/downstream" | "/app/integrations/upstream" | "/app/system/runtime" | "/app/system/peers";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/app";
  };
  "routes/workbench.tsx": {
    id: "routes/workbench";
    page: "/app/studio/chat";
  };
  "routes/studio-images.tsx": {
    id: "routes/studio-images";
    page: "/app/studio/images";
  };
  "routes/studio-audio.tsx": {
    id: "routes/studio-audio";
    page: "/app/studio/audio";
  };
  "routes/studio-rerank.tsx": {
    id: "routes/studio-rerank";
    page: "/app/studio/rerank";
  };
  "routes/studio-advanced.tsx": {
    id: "routes/studio-advanced";
    page: "/app/studio/advanced";
  };
  "routes/providers.tsx": {
    id: "routes/providers";
    page: "/app/control/providers";
  };
  "routes/accounts.tsx": {
    id: "routes/accounts";
    page: "/app/control/accounts";
  };
  "routes/control-runtime-config.tsx": {
    id: "routes/control-runtime-config";
    page: "/app/control/runtime-config";
  };
  "routes/control-controller.tsx": {
    id: "routes/control-controller";
    page: "/app/control/controller";
  };
  "routes/endpoints.tsx": {
    id: "routes/endpoints";
    page: "/app/control/endpoints";
  };
  "routes/control-models.tsx": {
    id: "routes/control-models";
    page: "/app/control/models";
  };
  "routes/observe-activity.tsx": {
    id: "routes/observe-activity";
    page: "/app/observe/activity";
  };
  "routes/requests.tsx": {
    id: "routes/requests";
    page: "/app/observe/requests";
  };
  "routes/request-detail.tsx": {
    id: "routes/request-detail";
    page: "/app/observe/requests/:requestId";
  };
  "routes/observe-logs.tsx": {
    id: "routes/observe-logs";
    page: "/app/observe/logs";
  };
  "routes/integrations-downstream.tsx": {
    id: "routes/integrations-downstream";
    page: "/app/integrations/downstream";
  };
  "routes/integrations-upstream.tsx": {
    id: "routes/integrations-upstream";
    page: "/app/integrations/upstream";
  };
  "routes/runtime.tsx": {
    id: "routes/runtime";
    page: "/app/system/runtime";
  };
  "routes/system-peers.tsx": {
    id: "routes/system-peers";
    page: "/app/system/peers";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/app-layout": typeof import("./app/routes/app-layout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/workbench": typeof import("./app/routes/workbench.tsx");
  "routes/studio-images": typeof import("./app/routes/studio-images.tsx");
  "routes/studio-audio": typeof import("./app/routes/studio-audio.tsx");
  "routes/studio-rerank": typeof import("./app/routes/studio-rerank.tsx");
  "routes/studio-advanced": typeof import("./app/routes/studio-advanced.tsx");
  "routes/providers": typeof import("./app/routes/providers.tsx");
  "routes/accounts": typeof import("./app/routes/accounts.tsx");
  "routes/control-runtime-config": typeof import("./app/routes/control-runtime-config.tsx");
  "routes/control-controller": typeof import("./app/routes/control-controller.tsx");
  "routes/endpoints": typeof import("./app/routes/endpoints.tsx");
  "routes/control-models": typeof import("./app/routes/control-models.tsx");
  "routes/observe-activity": typeof import("./app/routes/observe-activity.tsx");
  "routes/requests": typeof import("./app/routes/requests.tsx");
  "routes/request-detail": typeof import("./app/routes/request-detail.tsx");
  "routes/observe-logs": typeof import("./app/routes/observe-logs.tsx");
  "routes/integrations-downstream": typeof import("./app/routes/integrations-downstream.tsx");
  "routes/integrations-upstream": typeof import("./app/routes/integrations-upstream.tsx");
  "routes/runtime": typeof import("./app/routes/runtime.tsx");
  "routes/system-peers": typeof import("./app/routes/system-peers.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};