// Generated by packages/schema-tools/src/validate-schemas.ts generate-types
// Do not edit by hand.

export interface BenchmarkRun {
  run_id: string;
  suite_id: string;
  endpoint_id: string;
  started_at_ms: number;
  finished_at_ms: number;
  /**
   * @minItems 1
   */
  results: [
    {
      case_id: string;
      latency_ms: number;
      success: boolean;
      judge_score?: number;
    },
    ...{
      case_id: string;
      latency_ms: number;
      success: boolean;
      judge_score?: number;
    }[]
  ];
}


export interface BenchmarkSuite {
  suite_id: string;
  task_type: string;
  /**
   * @minItems 1
   */
  capability_targets: [string, ...string[]];
  /**
   * @minItems 1
   */
  cases: [
    {
      case_id: string;
      prompt_ref: string;
      expected_shape?: string;
    },
    ...{
      case_id: string;
      prompt_ref: string;
      expected_shape?: string;
    }[]
  ];
}


export interface CapabilityTaxonomy {
  version: string;
  /**
   * @minItems 1
   */
  capabilities: [
    {
      id: string;
      family: string;
      description: string;
    },
    ...{
      id: string;
      family: string;
      description: string;
    }[]
  ];
}


export interface DeclaredCapabilityProfile {
  endpoint_id: string;
  /**
   * @minItems 1
   */
  capabilities: [string, ...string[]];
  /**
   * @minItems 1
   */
  modalities: [string, ...string[]];
  max_context_tokens: number;
  tool_calling: {
    supported: boolean;
    style: 'openai' | 'json' | 'none';
  };
  supports_embeddings: boolean;
  platform_constraints?: string[];
}


export interface EndpointIdentity {
  endpoint_id: string;
  endpoint_kind: 'local_engine' | 'remote_api' | 'browser_engine' | 'dispatch_adapter';
  provider_kind:
    | 'acp'
    | 'mcp'
    | 'cli'
    | 'remote_openai_compat'
    | 'onnx'
    | 'mlx'
    | 'litertlm'
    | 'gguf'
    | 'webllm'
    | 'mediapipe_genai'
    | 'mediapipe_text';
  serving_source: string;
  model_id: string;
  package_id?: string;
  variant_id?: string;
  runtime_version: string;
  quantization?: string;
  precision?: string;
  host_class?: string;
  device_class?: string;
  region?: string;
  org_scope?: string;
  endpoint_version?: string;
}


export interface MetricEntry {
  value: number;
  source: 'measured' | 'declared' | 'default';
  raw?: {
    [k: string]: unknown;
  };
}


export interface JudgeScore {
  judge_id: string;
  case_id: string;
  score: number;
  rationale: string;
}


export interface ModelPackManifest {
  pack_id: string;
  version: string;
  /**
   * @minItems 1
   */
  models: [
    {
      model_id: string;
      artifact_ref: string;
    },
    ...{
      model_id: string;
      artifact_ref: string;
    }[]
  ];
}


export interface ObservedPerformanceProfile {
  endpoint_id: string;
  endpoint_version: string;
  measured_at_ms: number;
  measurement_window: {
    started_at_ms: number;
    ended_at_ms: number;
  };
  sample_size: number;
  sources: {
    benchmark_samples: number;
    live_request_samples: number;
  };
  judge_score?: number;
  quality_score?: number;
  latency_ms_p50: number;
  latency_ms_p95: number;
  tokens_per_sec?: number;
  cold_start_ms?: number;
  failure_rate: number;
  error_class_rates?: {
    [k: string]: number;
  };
  cost_per_1k_tokens_est?: number;
  currency?: string;
  freshness_score: number;
  confidence_score: number;
}


export interface PackageManifest {
  package_id: string;
  version: string;
  kind: string;
  entrypoints: string[];
  capability_exports?: string[];
}


export interface PlanSpec {
  plan_id: string;
  version: string;
  task_type: string;
  /**
   * @minItems 1
   */
  steps: [
    {
      step_id: string;
      description: string;
      inputs?: string[];
      outputs?: string[];
    },
    ...{
      step_id: string;
      description: string;
      inputs?: string[];
      outputs?: string[];
    }[]
  ];
}


export interface RoleBinding {
  binding_id: string;
  role_id: string;
  endpoint_id: string;
  status: 'active' | 'inactive' | 'disabled';
  policy_overrides: {
    [k: string]: unknown;
  };
  effective_capabilities: string[];
  effective_task_types: string[];
}


export interface RoleDefinition {
  role_id: string;
  name: string;
  description: string;
  role_kind: string;
  default_system_instructions: string;
  task_types_supported: string[];
  required_capabilities: string[];
  preferred_capabilities: string[];
  forbidden_capabilities: string[];
  tool_policy: {
    mode: 'disabled' | 'limited' | 'allowed';
    allowed_tools?: string[];
  };
  routing_policy_overrides: {
    [k: string]: unknown;
  };
  output_contracts: string[];
  safety_policy_refs: string[];
}


export interface RouterDecision {
  routing_decision_id: string;
  request_id: string;
  app_id: string;
  org_id: string | null;
  policy_snapshot: RoutingPolicy;
  eligibility: {
    endpoint_id: string;
    eligible: boolean;
    exclusions: {
      code:
        | 'CAPABILITY_MISSING'
        | 'FORBIDDEN_CAPABILITY_PRESENT'
        | 'MODALITY_UNSUPPORTED'
        | 'CONTEXT_TOO_SMALL'
        | 'TOOLS_UNSUPPORTED'
        | 'ROLE_NOT_ALLOWED'
        | 'TASK_NOT_SUPPORTED_BY_ROLE'
        | 'ROLE_BINDING_INACTIVE'
        | 'ROLE_BINDING_DISABLED'
        | 'ROLE_BINDING_TASK_NOT_ALLOWED'
        | 'ROLE_BINDING_CAPABILITY_MISSING'
        | 'POLICY_DENY_ENDPOINT'
        | 'POLICY_DENY_REMOTE'
        | 'ACCOUNT_DISABLED'
        | 'AUTH_UNAVAILABLE'
        | 'ENTITLEMENT_MISSING'
        | 'QUOTA_EXHAUSTED'
        | 'REGION_DISALLOWED'
        | 'DEPLOYMENT_CLASS_MISMATCH'
        | 'PACKAGE_NOT_INSTALLED'
        | 'VARIANT_INCOMPATIBLE'
        | 'PROVIDER_OFFLINE'
        | 'BUDGET_EXCEEDED'
        | 'REVOKED';
      detail: string;
    }[];
  }[];
  scored_candidates: {
    endpoint_id: string;
    total_score: number;
    metric_breakdown: {
      quality: MetricEntry;
      latency: MetricEntry;
      throughput: MetricEntry;
      cost: MetricEntry;
      reliability: MetricEntry;
      preference: MetricEntry;
    };
    tie_break: {
      quality: number;
      latency_ms: number;
      reliability: number;
      endpoint_id: string;
    };
  }[];
  chosen_endpoint_id: string;
  fallback_endpoint_ids: string[];
  selection_reasons: (
    | 'BEST_TOTAL_SCORE'
    | 'MEASURED_PROFILE_USED'
    | 'DECLARED_PROFILE_USED'
    | 'DEFAULT_PROFILE_USED'
    | 'LOCAL_PREFERENCE_APPLIED'
    | 'REMOTE_PREFERENCE_APPLIED'
    | 'CONTINUITY_AFFINITY_APPLIED'
    | 'CACHE_AFFINITY_APPLIED'
    | 'ROUTING_MODEL_PREFERENCE_APPLIED'
    | 'BUDGET_OPTIMIZATION'
    | 'LOW_LATENCY_TARGET_MET'
    | 'HIGH_QUALITY_TARGET_MET'
    | 'ROLE_POLICY_APPLIED'
    | 'TASK_POLICY_APPLIED'
    | 'FALLBACK_CHAIN_COMPUTED'
  )[];
  used_measured: boolean;
  used_declared: boolean;
  scoring_version: string;
}


export interface RoutingPolicy {
  policy_id?: string;
  strategy: 'balanced' | 'cost' | 'latency' | 'quality';
  compute_preference: 'auto' | 'local' | 'remote' | 'hybrid';
  prefer_local?: boolean;
  budget_mode?: 'strict' | 'advisory' | 'disabled';
  /**
   * @minItems 1
   */
  tie_break_order?: [string, ...string[]];
  required_capabilities: string[];
  required_modalities: string[];
  require_tools: boolean;
  deny_endpoints: string[];
  allow_endpoints: string[];
  deny_provider_kinds: string[];
  allow_provider_kinds: string[];
  budget: {
    enabled: boolean;
    currency: string;
    max_cost_per_request?: number;
    target_cost_per_request?: number;
  };
  privacy: {
    allow_remote: boolean;
  };
  targets: {
    latency_target_ms: number;
    latency_max_ms: number;
    throughput_target_tps: number;
  };
}


export interface TaskDefinition {
  task_type: string;
  description: string;
  required_inputs: string[];
  required_capabilities: string[];
  preferred_capabilities: string[];
  quality_metrics: string[];
  allowed_roles: string[];
  default_benchmark_suites: string[];
}


export interface TaskExecutionProfile {
  task_type: string;
  role_id: string;
  required_capabilities: string[];
  preferred_capabilities: string[];
  routing_policy_patch: RoutingPolicy;
}


export interface TraceEvent {
  event_id: string;
  trace_id: string;
  span_id?: string;
  request_id: string;
  routing_decision_id: string;
  timestamp_ms: number;
  event_type:
    | 'router.decision.created'
    | 'trace.span.opened'
    | 'trace.span.closed'
    | 'usage.event.created'
    | 'profile.sample.recorded'
    | 'profile.updated';
  payload: {
    [k: string]: unknown;
  };
}


export interface TraceSpan {
  trace_id: string;
  span_id: string;
  parent_span_id?: string;
  request_id: string;
  routing_decision_id: string;
  span_type:
    | 'router.eligibility'
    | 'router.scoring'
    | 'router.selection'
    | 'provider.load'
    | 'provider.queue'
    | 'provider.prefill'
    | 'provider.decode'
    | 'tool.execution'
    | 'router.fallback'
    | 'router.retry'
    | 'request.failure';
  started_at_ms: number;
  ended_at_ms: number;
  status: 'ok' | 'error' | 'cancelled';
  attributes?: {
    [k: string]: string | number | boolean;
  };
}


export interface UsageEvent {
  event_id: string;
  timestamp_ms: number;
  app_id: string;
  org_id?: string;
  request_id: string;
  routing_decision_id: string;
  endpoint_id: string;
  model_id?: string;
  package_id?: string;
  provider_kind: string;
  tokens_in: number;
  tokens_out: number;
  latency_ms: number;
  cost_estimate?: number;
  currency?: string;
  error_class?: string;
  sample_source?: 'live_request' | 'benchmark';
}
