// Generated by packages/schema-tools/src/validate-schemas.ts generate-types
// Do not edit by hand.

export interface BenchmarkRun {
  run_id: string;
  suite_id: string;
  endpoint_id: string;
  started_at_ms: number;
  finished_at_ms: number;
  /**
   * @minItems 1
   */
  results: [
    {
      case_id: string;
      latency_ms: number;
      success: boolean;
      judge_score?: number;
    },
    ...{
      case_id: string;
      latency_ms: number;
      success: boolean;
      judge_score?: number;
    }[],
  ];
}

export interface BenchmarkSuite {
  suite_id: string;
  task_type: string;
  /**
   * @minItems 1
   */
  capability_targets: [string, ...string[]];
  /**
   * @minItems 1
   */
  cases: [
    {
      case_id: string;
      prompt_ref: string;
      expected_shape?: string;
    },
    ...{
      case_id: string;
      prompt_ref: string;
      expected_shape?: string;
    }[],
  ];
}

export interface CapabilityTaxonomy {
  version: string;
  /**
   * @minItems 1
   */
  capabilities: [
    {
      id: string;
      family: string;
      description: string;
    },
    ...{
      id: string;
      family: string;
      description: string;
    }[],
  ];
}

export interface DeclaredCapabilityProfile {
  endpoint_id: string;
  /**
   * @minItems 1
   */
  capabilities: [string, ...string[]];
  /**
   * @minItems 1
   */
  modalities: [string, ...string[]];
  max_context_tokens: number;
  tool_calling: boolean;
  supports_embeddings: boolean;
  platform_constraints: string[];
}

export interface EndpointIdentity {
  endpoint_id: string;
  endpoint_kind: string;
  provider_kind: string;
  serving_source: string;
  model_id: string;
  package_id: string;
  variant_id: string;
  runtime_version: string;
  quantization: string;
  precision: string;
  host_class: string;
  device_class: string;
  region: string;
  org_scope: string;
}

export interface JudgeScore {
  judge_id: string;
  case_id: string;
  score: number;
  rationale: string;
}

export interface ModelPackManifest {
  pack_id: string;
  version: string;
  /**
   * @minItems 1
   */
  models: [
    {
      model_id: string;
      artifact_ref: string;
    },
    ...{
      model_id: string;
      artifact_ref: string;
    }[],
  ];
}

export interface ObservedPerformanceProfile {
  endpoint_id: string;
  measured_at_ms: number;
  measurement_window: string;
  sample_size: number;
  judge_score: number;
  latency_ms_p50: number;
  latency_ms_p95: number;
  tokens_per_sec: number;
  cold_start_ms: number;
  failure_rate: number;
  error_class_rates: {
    [k: string]: number;
  };
  cost_per_1k_tokens_est: number;
  currency: string;
  freshness_score: number;
  confidence_score: number;
}

export interface PackageManifest {
  package_id: string;
  version: string;
  kind: string;
  entrypoints: string[];
  capability_exports?: string[];
}

export interface PlanSpec {
  plan_id: string;
  version: string;
  task_type: string;
  /**
   * @minItems 1
   */
  steps: [
    {
      step_id: string;
      description: string;
      inputs?: string[];
      outputs?: string[];
    },
    ...{
      step_id: string;
      description: string;
      inputs?: string[];
      outputs?: string[];
    }[],
  ];
}

export interface RoleBinding {
  binding_id: string;
  role_id: string;
  endpoint_id: string;
  status: "active" | "disabled" | "experimental";
  policy_overrides: {
    [k: string]: unknown;
  };
  effective_capabilities: string[];
  effective_task_types: string[];
}

export interface RoleDefinition {
  role_id: string;
  name: string;
  description: string;
  role_kind: string;
  default_system_instructions: string;
  task_types_supported: string[];
  required_capabilities: string[];
  preferred_capabilities: string[];
  forbidden_capabilities: string[];
  tool_policy: {
    mode: "disabled" | "limited" | "allowed";
    allowed_tools?: string[];
  };
  routing_policy_overrides: {
    [k: string]: unknown;
  };
  output_contracts: string[];
  safety_policy_refs: string[];
}

export interface RouterDecision {
  routing_decision_id: string;
  request_id: string;
  policy_snapshot: RoutingPolicy;
  eligible_candidates: string[];
  ineligible_candidates: {
    endpoint_id: string;
    /**
     * @minItems 1
     */
    reasons: [string, ...string[]];
  }[];
  scored_candidates: {
    endpoint_id: string;
    score: number;
  }[];
  chosen_endpoint_id: string;
  fallback_endpoint_ids: string[];
  /**
   * @minItems 1
   */
  selection_reasons: [string, ...string[]];
  used_measured: boolean;
  used_declared: boolean;
  scoring_version: string;
}
export interface RoutingPolicy {
  policy_id: string;
  strategy: "balanced" | "low-latency" | "high-quality" | "low-cost";
  prefer_local: boolean;
  budget_mode: "strict" | "advisory" | "disabled";
  /**
   * @minItems 1
   */
  tie_break_order: [string, ...string[]];
}

export interface RoutingPolicy {
  policy_id: string;
  strategy: "balanced" | "low-latency" | "high-quality" | "low-cost";
  prefer_local: boolean;
  budget_mode: "strict" | "advisory" | "disabled";
  /**
   * @minItems 1
   */
  tie_break_order: [string, ...string[]];
}

export interface TaskDefinition {
  task_type: string;
  description: string;
  required_inputs: string[];
  required_capabilities: string[];
  preferred_capabilities: string[];
  quality_metrics: string[];
  allowed_roles: string[];
  default_benchmark_suites: string[];
}

export interface TaskExecutionProfile {
  task_type: string;
  required_capabilities: string[];
  preferred_capabilities: string[];
  required_modalities: string[];
  output_constraints: string[];
  evaluation_suites: string[];
  default_routing_strategy: string;
}

export interface TraceEvent {
  event_id: string;
  trace_id: string;
  span_id: string;
  timestamp_ms: number;
  event_type: string;
  message: string;
  attributes?: {
    [k: string]: string | number | boolean;
  };
}

export interface TraceSpan {
  trace_id: string;
  span_id: string;
  parent_span_id?: string;
  name: string;
  started_at_ms: number;
  ended_at_ms: number;
  status: "ok" | "error" | "cancelled";
  attributes?: {
    [k: string]: string | number | boolean;
  };
}

export interface UsageEvent {
  event_id: string;
  timestamp_ms: number;
  app_id: string;
  org_id: string;
  request_id: string;
  routing_decision_id: string;
  endpoint_id: string;
  model_id: string;
  package_id: string;
  provider_kind: string;
  tokens_in: number;
  tokens_out: number;
  latency_ms: number;
  cost_estimate: number;
  currency: string;
  error_class: string;
}
