import { spawn } from "node:child_process";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { Command } from "commander";
import { compile } from "json-schema-to-typescript";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);
const repoRoot = path.resolve(__dirname, "..", "..", "..");
const schemaDir = path.join(repoRoot, "protocol", "schemas");
const protocolTypesOutput = path.join(
  repoRoot,
  "packages",
  "protocol-types",
  "src",
  "generated.ts",
);
const biomeExecutable = path.join(
  repoRoot,
  "node_modules",
  ".bin",
  process.platform === "win32" ? "biome.CMD" : "biome",
);

type JsonSchema = Record<string, unknown>;

export async function loadSchemas(): Promise<Array<{ fileName: string; schema: JsonSchema }>> {
  const names = (await readdir(schemaDir)).filter((name) => name.endsWith(".schema.json")).sort();
  const schemas = await Promise.all(
    names.map(async (fileName) => ({
      fileName,
      schema: JSON.parse(await readFile(path.join(schemaDir, fileName), "utf8")) as JsonSchema,
    })),
  );

  return schemas.map(({ fileName, schema }) => ({
    fileName,
    schema: {
      $id: fileName,
      ...schema,
    },
  }));
}

export async function validateSchemas(): Promise<void> {
  const ajvModule: typeof import("ajv/dist/2020.js") = require("ajv/dist/2020.js");
  const formatsModule: typeof import("ajv-formats") = require("ajv-formats");
  const Ajv2020 = ajvModule.default;
  const addFormats = formatsModule.default;
  const ajv = new Ajv2020({
    allErrors: true,
    strict: true,
  });
  addFormats(ajv);

  const schemas = await loadSchemas();
  for (const { schema } of schemas) {
    ajv.addSchema(schema, String(schema.$id));
  }
  for (const { fileName, schema } of schemas) {
    ajv.compile(schema);
    if (typeof schema.title !== "string" || !schema.title) {
      throw new Error(`Schema ${fileName} is missing a string title.`);
    }
  }

  console.log(`Validated ${schemas.length} schema file(s).`);
}

export async function generateProtocolTypes(): Promise<void> {
  const schemas = await loadSchemas();
  const blocks: string[] = [
    "// Generated by packages/schema-tools/src/validate-schemas.ts generate-types",
    "// Do not edit by hand.",
    "",
  ];

  for (const { fileName, schema } of schemas) {
    blocks.push(
      await compile(schema, String(schema.title), {
        bannerComment: "",
        cwd: schemaDir,
        style: { singleQuote: true },
      }),
    );
    blocks.push("");
    console.log(`Generated types for ${fileName}`);
  }

  await writeFile(protocolTypesOutput, `${blocks.join("\n").trim()}\n`, "utf8");
  await formatGeneratedTypes();
}

async function formatGeneratedTypes(): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const command =
      process.platform === "win32"
        ? {
            file: "cmd.exe",
            args: ["/c", biomeExecutable, "format", "--write", protocolTypesOutput],
          }
        : { file: biomeExecutable, args: ["format", "--write", protocolTypesOutput] };
    const child = spawn(command.file, command.args, {
      cwd: repoRoot,
      stdio: "inherit",
      shell: false,
    });

    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(
        new Error(
          `Biome formatting failed for generated protocol types with exit code ${code ?? "unknown"}.`,
        ),
      );
    });
  });
}

async function main(): Promise<void> {
  const program = new Command()
    .name("validate-schemas")
    .argument("<mode>", "validate | generate-types");

  program.parse(process.argv);
  const [mode] = program.args;

  if (mode === "validate") {
    await validateSchemas();
    return;
  }

  if (mode === "generate-types") {
    await generateProtocolTypes();
    return;
  }

  throw new Error(`Unsupported mode: ${mode}`);
}

if (process.argv[1] === __filename) {
  await main();
}
