export const EXCLUSION_REASON_CODES = [
  "CAPABILITY_MISSING",
  "MODALITY_UNSUPPORTED",
  "CONTEXT_TOO_SMALL",
  "TOOLS_UNSUPPORTED",
  "POLICY_DENY_ENDPOINT",
  "POLICY_DENY_REMOTE",
  "BUDGET_EXCEEDED",
  "PROVIDER_OFFLINE",
  "VARIANT_INCOMPATIBLE",
  "ENTITLEMENT_MISSING",
  "REVOKED",
] as const;

export const SELECTION_REASON_CODES = [
  "BEST_TOTAL_SCORE",
  "MEASURED_PROFILE_USED",
  "DECLARED_PROFILE_USED",
  "DEFAULT_PROFILE_USED",
  "LOCAL_PREFERENCE_APPLIED",
  "REMOTE_PREFERENCE_APPLIED",
  "BUDGET_OPTIMIZATION",
  "LOW_LATENCY_TARGET_MET",
  "HIGH_QUALITY_TARGET_MET",
  "FALLBACK_CHAIN_COMPUTED",
] as const;
