/**
 * Embed the vendored v1.1 contract schemas as a TypeScript module so the packaged
 * runtime carries them without depending on files next to the bundle.
 *
 * Usage: node scripts/embed-schemas.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, "..");
const files = {
  routeLearning: "route-learning-contracts.schema.json",
  trackBStorage: "track-b-storage-contracts.schema.json",
  trackBProjection: "track-b-projection-contracts.schema.json",
};

const entries = Object.entries(files).map(([name, file]) => {
  const schema = JSON.parse(readFileSync(join(packageRoot, "schemas", file), "utf8"));
  return `export const ${name}Schema = ${JSON.stringify(schema, null, 2)} as const;`;
});

const source = `// Generated by scripts/embed-schemas.mjs from schemas/*.json. Do not edit by hand.
${entries.join("\n\n")}
`;
writeFileSync(join(packageRoot, "src", "v1.1-schemas.generated.ts"), source, "utf8");
process.stdout.write(`wrote src/v1.1-schemas.generated.ts (${source.length} bytes)\n`);
