import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";

type LifecycleRecord = { readonly id: string; readonly lifecycle: "ready" | "degraded" | "stopped"; readonly enabled: boolean; readonly channel: string; readonly scope: string; readonly authorizationEpoch: number; readonly health: { readonly available: boolean; readonly routingDependency: boolean; readonly reason?: string } };
type StorageRecord = { readonly id: string; readonly category: string; readonly tier: string; readonly scope: string; readonly bytes: number; readonly count: number; readonly holds?: number; readonly leases?: number; readonly conflicts?: readonly string[] };
type BridgeState = { readonly schemaVersion: "role-model.track-b-production-bridge.v1"; readonly protocolVersion: "1.0"; readonly revision: number; readonly generatedAt: string; readonly extensions: readonly LifecycleRecord[]; readonly storageServices: readonly StorageRecord[]; readonly retention: { readonly managedPolicy: boolean; readonly receipts: readonly unknown[]; readonly activeJob: unknown } };
const EMPTY_STATE: BridgeState = { schemaVersion: "role-model.track-b-production-bridge.v1", protocolVersion: "1.0", revision: 0, generatedAt: "1970-01-01T00:00:00.000Z", extensions: [], storageServices: [], retention: { managedPolicy: false, receipts: [], activeJob: null } };
const validate = (value: BridgeState): BridgeState => { if (value?.schemaVersion !== EMPTY_STATE.schemaVersion || value.protocolVersion !== "1.0" || !Number.isInteger(value.revision) || value.revision < 0 || !Array.isArray(value.extensions) || !Array.isArray(value.storageServices) || !value.retention) throw new Error("invalid Track B production bridge state"); const ids=new Set<string>(); for(const row of value.extensions){if(!row.id||ids.has(row.id)||!["ready","degraded","stopped"].includes(row.lifecycle)||row.health?.available!==(row.lifecycle==="ready"))throw new Error("invalid or duplicate extension lifecycle record");ids.add(row.id)} for(const row of value.storageServices)if(!row.id||!row.category||!Number.isFinite(row.bytes)||row.bytes<0||!Number.isInteger(row.count)||row.count<0)throw new Error("invalid storage service record"); return value; };
const readState = async (statePath: string): Promise<BridgeState> => { try { return validate(JSON.parse(await readFile(statePath,"utf8")) as BridgeState); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return EMPTY_STATE; throw error; } };
const writeState = async (statePath: string, state: BridgeState) => { await mkdir(path.dirname(statePath),{recursive:true}); const temporary=`${statePath}.${process.pid}.tmp`; await writeFile(temporary,`${JSON.stringify(state,null,2)}\n`,"utf8"); await rename(temporary,statePath); };

export function createTrackBOperations({ statePath, catalog }: { readonly statePath: string; readonly catalog: readonly Record<string, unknown>[] }) {
  return {
    async listExtensions(): Promise<readonly unknown[]> { const state=await readState(statePath),byId=new Map(state.extensions.map(row=>[row.id,row])); return catalog.map(entry=>{const id=String(entry.id??""),actual=byId.get(id); return actual?{...entry,...actual,installed:true}:{...entry,installed:false,enabled:false,lifecycle:"unavailable",channel:"production",scope:"global",authorizationEpoch:0,health:{available:false,routingDependency:Boolean(entry.routingDependency),reason:"not_registered_with_private_supervisor"}};}); },
    async readStorageRetention(): Promise<unknown> { const state=await readState(statePath),categories=state.storageServices.map(row=>({id:row.category,tier:row.tier,scope:row.scope,bytes:row.bytes,count:row.count,serviceId:row.id})); return {revision:state.revision,totalBytes:categories.reduce((sum,row)=>sum+row.bytes,0),categories,managedPolicy:state.retention.managedPolicy,conflicts:state.storageServices.flatMap(row=>(row.conflicts??[]).map(reason=>({serviceId:row.id,reason}))),holds:state.storageServices.reduce((sum,row)=>sum+(row.holds??0),0),leases:state.storageServices.reduce((sum,row)=>sum+(row.leases??0),0),receipts:state.retention.receipts,activeJob:state.retention.activeJob}; },
    async dryRunStorageRetention(): Promise<unknown> { const state=await readState(statePath); if(state.retention.managedPolicy)throw new Error("storage retention is controlled by managed policy"); const affectedCount=state.storageServices.reduce((sum,row)=>sum+row.count,0),totalBytes=state.storageServices.reduce((sum,row)=>sum+row.bytes,0),conflictCount=state.storageServices.reduce((sum,row)=>sum+(row.conflicts?.length??0),0),manifest={revision:state.revision,affectedCount,totalBytes,conflictCount,serviceIds:state.storageServices.map(row=>row.id).sort()},receipt={id:`dry-${createHash("sha256").update(JSON.stringify(manifest)).digest("hex").slice(0,16)}`,status:"preview",affectedCount,rollbackAvailable:true,sourceRevision:state.revision}; const next:BridgeState={...state,revision:state.revision+1,generatedAt:new Date().toISOString(),retention:{...state.retention,receipts:[...state.retention.receipts,receipt].slice(-100)}}; await writeState(statePath,next); return this.readStorageRetention(); },
  };
}
